"""Build the sim2 notebook from the submitted baseline notebook.

usage: python tools/make_sim2_notebook.py <baseline.ipynb> <out.ipynb> [--shard N] [--size N]

The output contains the baseline's code, so it must never be committed (this repo is public).
"""
import argparse
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SIM_DIR = os.path.join(HERE, 'sim2')

SMOKE_MARK = '# SMOKE switch'
ENG_MARK = '# Our engine (two-ranker'
CELL6_MARK = '# all molecules -> base lists'
CELL6_SCORE = 'score = rank_score(np.concatenate([X, F], 1), list(FEATURES) + list(names))'
CELL7_MARK = '# ICEBERG post-ranker'
CELL8_MARK = '# gated PubChem merge'
CELL9_MARK = 'ALPHA, KRR ='
GL_BUDGET_LIT = ', 1.0, 4000'


def code_cell(src):
    return dict(cell_type='code', execution_count=None, metadata={}, outputs=[],
                source=src.splitlines(keepends=True))


def read(name):
    return open(os.path.join(SIM_DIR, name)).read()


def build_setup(source, shard=0, size=500):
    assert source in ('train', 'external')
    s = read('sim_setup.py').replace('SHARD, SHARD_SIZE = 0, 500', f'SHARD, SHARD_SIZE = {shard}, {size}')
    s = s.replace("SOURCE = 'train'", f"SOURCE = '{source}'")
    assert s.count('# @@SELECT@@\n') == 1
    return s.replace('# @@SELECT@@\n', read(f'select_{source}.py'))


def find_cell(cells, mark):
    hits = [i for i, c in enumerate(cells) if c['cell_type'] == 'code' and mark in ''.join(c['source'])]
    assert len(hits) == 1, f'expected exactly one cell containing {mark!r}, found {len(hits)}'
    return hits[0]


def patch_cell6(src):
    lines = src.splitlines(keepends=True)
    hits = [i for i, l in enumerate(lines) if l.strip() == CELL6_SCORE]
    assert len(hits) == 1, 'ranker scoring line not found in the base-list cell'
    i = hits[0]
    indent = lines[i][:len(lines[i]) - len(lines[i].lstrip())]
    lines.insert(i + 1, f'{indent}_simdump(mid, C, np.concatenate([X, F], 1), list(FEATURES) + list(names), score)\n')
    out = ''.join(lines)
    assert out.count('(gi + 1) % 25 == 0') == 1, 'progress-print line not found in the base-list cell'
    return out.replace('(gi + 1) % 25 == 0', '(gi + 1) % 5 == 0')


ENG_HOOK = 'E.find = _find\\n'
ENG_HOOK_NEW = ENG_HOOK + '    if os.environ.get("SIM2_ENG_PATCH"): exec(open(os.environ["SIM2_ENG_PATCH"]).read())\\n'


def patch_engine2(src):
    # the engine-2 runner is a string literal in this cell: hook a patch file in right after its find() override
    assert src.count(ENG_HOOK) == 1, 'engine-2 runner hook point not found'
    return src.replace(ENG_HOOK, ENG_HOOK_NEW)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('baseline')
    ap.add_argument('out')
    ap.add_argument('--shard', type=int, default=0)
    ap.add_argument('--size', type=int, default=500)
    ap.add_argument('--source', choices=['train', 'external'], default='external')
    a = ap.parse_args()

    nb = json.load(open(a.baseline))
    cells = nb['cells']
    for c in cells:
        if c['cell_type'] == 'code':
            c['outputs'], c['execution_count'] = [], None

    setup = build_setup(a.source, a.shard, a.size)
    cells[find_cell(cells, SMOKE_MARK)] = code_cell(setup)

    i2 = find_cell(cells, ENG_MARK)
    cells[i2] = code_cell(patch_engine2(''.join(cells[i2]['source'])))

    i6 = find_cell(cells, CELL6_MARK)
    cells[i6] = code_cell(patch_cell6(''.join(cells[i6]['source'])))
    cells.insert(i6 + 1, code_cell('import copy\nBASE0 = copy.deepcopy(BASE)   # sim2: ranker lists before ICEBERG/GLACIER\n'))

    i7 = find_cell(cells, CELL7_MARK)
    cells.insert(i7 + 1, code_cell('BASE_POST_ICE = copy.deepcopy(BASE)   # sim2: lists after ICEBERG/GLACIER, before the PubChem merge\n'))

    i8 = find_cell(cells, CELL8_MARK)
    cells.insert(i8 + 1, code_cell("import shutil\nshutil.copy('submission.csv', os.path.join(SIM_OUT, 'sub_v4.csv'))   # sim2: before final fusion\n"))

    find_cell(cells, CELL9_MARK)
    i7 = find_cell(cells, CELL7_MARK)
    src7 = ''.join(cells[i7]['source'])
    assert src7.count(GL_BUDGET_LIT) == 1, 'GLACIER budget literal not found'
    cells[i7] = code_cell(src7.replace(GL_BUDGET_LIT, ', 1.0, SIM_GL_BUDGET'))
    cells.append(code_cell(read('sim_finish.py')))

    # a timestamped progress line before every step after the setup cell, so a stalled run shows where it is
    i_setup = find_cell(cells, '# sim2 setup')
    out = cells[:i_setup + 1]
    for c in cells[i_setup + 1:]:
        if c['cell_type'] == 'code':
            first = ''.join(c['source']).strip().splitlines()[0][:70].replace("'", '')
            out.append(code_cell(f"sim2_mark('{first}')\n"))
        out.append(c)
    nb['cells'] = cells = out

    cells.insert(0, dict(cell_type='markdown', metadata={}, source=[
        f'# casmi26-sim2-build ({a.source} questions, shard {a.shard}, {a.size} queries)\n',
        'Generated by tools/make_sim2_notebook.py from the submitted baseline. Runs the unchanged pipeline on held-out\n',
        'training compounds and saves labelled outputs to /kaggle/working/sim_out. Save the output as a PRIVATE dataset.\n']))
    json.dump(nb, open(a.out, 'w'), indent=1)
    print('wrote', a.out)


if __name__ == '__main__':
    main()
